//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersona
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Dpi { get; set; }
        public string Direccion { get; set; }
        public bool Genero { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Escolaridad { get; set; }
        public bool Activo { get; set; }
    }
}
